CREATE TABLE EVENTO
(
  ID integer NOT NULL AUTO_INCREMENT,
  NOMBRE varchar(120) NOT NULL,
  FECHA_INICIO date NOT NULL,
  FECHA_FIN date NOT NULL,
  SUSPENDIDO char(1) DEFAULT 'N',
  CONSTRAINT ID_EVENTO PRIMARY KEY (ID)
);

CREATE TABLE EVENTO_REFERENCIA_PRODUCTO
(
  ID integer NOT NULL AUTO_INCREMENT,
  EVENTO_ID integer NOT NULL,
  REFERENCIA varchar(60) NOT NULL,
  PRECIO_ANTIGUO integer NOT NULL,
  PRECIO_NUEVO integer NOT NULL,
  CONSTRAINT PK_EVENTO_REFERENCIA_PRODUCTO PRIMARY KEY (ID)
);

ALTER TABLE EVENTO_REFERENCIA_PRODUCTO ADD CONSTRAINT FK_EVENTO_REFERENCIA_PRODUCTO_
  FOREIGN KEY (EVENTO_ID) REFERENCES EVENTO (ID);
